### ISSUE TITLE
Customizing the TagCell

### ISSUE THREAD

**Issue by RanjitKadam** [moonlsd/TagFlowExample#2]
Hey, lucifer, thanks for creating this project and explaining it, it was very helpful. 

Actually I am trying to customize the cell, and it should look like the below picture.
![flowcell](https://cloud.githubusercontent.com/assets/16592090/16456870/1b916446-3e37-11e6-9ce7-2835d8b2cef1.png)

So as you can see in the above image, their is Music and an arrow mark, so both  should be clicked separately, when selecting, because it has different actions. Music click will do a different action and arrow click will do a different action.

So can you please help me out in doing this.

**Comment by RanjitKadam** [comment]
@luceefer can you please look at the issue.

**Comment by moonlsd** [comment]
@RanjitKadam, sorry for late reply. I have GitHub notification turned off, so I don't know about your comment :(

About the cell, I suggest doing the following things:
1. You know that, the FlowLayout which we customized, is responsible for calculating cell size and place cell in right position. With your cell, you should update the method in the LayoutDelegate class to correctly calculate width and height of your cell, corresponding with the text. For example: Music take 100 points wide, plus left and right spacing, plus size of arrow mark. Do not forget to add spacing between cells.
2. About buttons click, you should extends UICollectionViewCell, then drag your button outlets to this class, handle click from cell class itself. You can send click events to your controller by create a CellDelegate with two distinct functions for your two buttons.

Please try and hope my answer is not too late for you.

**Comment by RanjitKadam** [comment]
@luceefer, Thanks for replying, I managed to do this, here is my flowLayout code, but some times the cells donot arrange them properly, their is gap between two cells. here is my flowLayout code

import UIKit

```
class FlowLayout: UICollectionViewFlowLayout {

    override func layoutAttributesForElementsInRect(rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        var newAttributesForElementsInRect = [UICollectionViewLayoutAttributes]()        
        // unwrap super's attributes
        guard let attributesForElementsInRect = super.layoutAttributesForElementsInRect(rect) else { return nil }

        // modify attributes

        var leftMargin: CGFloat = 8.0;

        for attributes in attributesForElementsInRect {

            let itemAttributesCopy = attributes.copy() as! UICollectionViewLayoutAttributes

           print("attCopy",itemAttributesCopy.frame.size.width)
            print("left",leftMargin)
            print("collWidth",self.collectionView?.frame.size.width)

            print("sectionInset",self.sectionInset.left)

            if( itemAttributesCopy.frame.size.width + leftMargin > self.collectionView?.frame.size.width)
            {
                leftMargin = 8.0
            }
            if (itemAttributesCopy.frame.origin.x == self.sectionInset.left) {
                leftMargin = self.sectionInset.left
            } else {

                 print("itemAttributeCopy",itemAttributesCopy.frame)

                var newLeftAlignedFrame = itemAttributesCopy.frame
                newLeftAlignedFrame.origin.x = leftMargin
                itemAttributesCopy.frame = newLeftAlignedFrame
                 print("newFrame",newLeftAlignedFrame)
            }
            leftMargin += itemAttributesCopy.frame.size.width + 8
             print("finalleftMargin",leftMargin)



            newAttributesForElementsInRect.append(itemAttributesCopy)
        }

        return newAttributesForElementsInRect
    }
}
```

Can you tell me whether it is correct?

**Comment by moonlsd** [comment]
@RanjitKadam, I can not tell you whether your code is correct or not, but I prefer to talk about how it work.
First, the problem here is, we want to calculate exact left position of the cell. Also exact width of the cell too. Note that, the height is not too important.
Second, because of auto-layout and other things, width of the cell can be inaccurate when this method is called, my suggestion is manually calculate the width too, beside the left. Mostly, the layout works incorrectly because of:
            leftMargin += itemAttributesCopy.frame.size.width + 8
**This line may not correctly calculate width of item.**

Finally, you already know that value 8 is manually inserted padding, right? For example, 8 shall be space between leading edge of UICollectionView to leading edge of first cell in each line, and 8 shall be space between cells too.

**Comment by RanjitKadam** [comment]
@luceefer , I have few doubts,
1) exact left position of the cell, is w.r.t to the other cell or w.r.t to the collectionView
2) How to calculate exact width of cell manually?

**Comment by moonlsd** [comment]
@RanjitKadam 
1. To the collectionView.
2. ExactWidth of cell = width of all elements inside cell plus all horizontal spaces

The problem here, is text.
If you have image, button, then you should have their widths already.
But with text, you should calculate its width, for example:
- "Music" -> take 60 point with font size 14
- "Stream" -> take 72 point with font size 14

Refer to http://stackoverflow.com/questions/19128797/calculating-uilabel-text-size for calculating text size, take width of calculated frame. Add add to your calculation above.

Do not forget that, maximum width shall not exceed width of the collection view itself.
